/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PrintRouteImport } from './routes/print'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WeekRouteImport } from './routes/week'
import { Route as MoreAboutRouteImport } from './routes/more.about'
import { Route as MoreClashRouteImport } from './routes/more.clash'
import { Route as MoreExploreRouteImport } from './routes/more.explore'
import { Route as MoreRoomsRouteImport } from './routes/more.rooms'
import { Route as MoreSettingsRouteImport } from './routes/more.settings'
import { Route as MoreShareRouteImport } from './routes/more.share'
import { Route as MoreTeachersRouteImport } from './routes/more.teachers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreAboutRoute = MoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MoreRoute,
} as any)
const MoreClashRoute = MoreClashRouteImport.update({
  id: '/clash',
  path: '/clash',
  getParentRoute: () => MoreRoute,
} as any)
const MoreExploreRoute = MoreExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MoreRoute,
} as any)
const MoreRoomsRoute = MoreRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => MoreRoute,
} as any)
const MoreSettingsRoute = MoreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MoreRoute,
} as any)
const MoreShareRoute = MoreShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => MoreRoute,
} as any)
const MoreTeachersRoute = MoreTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => MoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/more': typeof MoreRouteWithChildren
  '/print': typeof PrintRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
  '/more/about': typeof MoreAboutRoute
  '/more/clash': typeof MoreClashRoute
  '/more/explore': typeof MoreExploreRoute
  '/more/rooms': typeof MoreRoomsRoute
  '/more/settings': typeof MoreSettingsRoute
  '/more/share': typeof MoreShareRoute
  '/more/teachers': typeof MoreTeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/more': typeof MoreRouteWithChildren
  '/print': typeof PrintRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
  '/more/about': typeof MoreAboutRoute
  '/more/clash': typeof MoreClashRoute
  '/more/explore': typeof MoreExploreRoute
  '/more/rooms': typeof MoreRoomsRoute
  '/more/settings': typeof MoreSettingsRoute
  '/more/share': typeof MoreShareRoute
  '/more/teachers': typeof MoreTeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/more': typeof MoreRouteWithChildren
  '/print': typeof PrintRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
  '/more/about': typeof MoreAboutRoute
  '/more/clash': typeof MoreClashRoute
  '/more/explore': typeof MoreExploreRoute
  '/more/rooms': typeof MoreRoomsRoute
  '/more/settings': typeof MoreSettingsRoute
  '/more/share': typeof MoreShareRoute
  '/more/teachers': typeof MoreTeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changes'
    | '/more'
    | '/print'
    | '/sitemap.xml'
    | '/week'
    | '/more/about'
    | '/more/clash'
    | '/more/explore'
    | '/more/rooms'
    | '/more/settings'
    | '/more/share'
    | '/more/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changes'
    | '/more'
    | '/print'
    | '/sitemap.xml'
    | '/week'
    | '/more/about'
    | '/more/clash'
    | '/more/explore'
    | '/more/rooms'
    | '/more/settings'
    | '/more/share'
    | '/more/teachers'
  id:
    | '__root__'
    | '/'
    | '/changes'
    | '/more'
    | '/print'
    | '/sitemap.xml'
    | '/week'
    | '/more/about'
    | '/more/clash'
    | '/more/explore'
    | '/more/rooms'
    | '/more/settings'
    | '/more/share'
    | '/more/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangesRoute: typeof ChangesRoute
  MoreRoute: typeof MoreRouteWithChildren
  PrintRoute: typeof PrintRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeekRoute: typeof WeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/about': {
      id: '/more/about'
      path: '/about'
      fullPath: '/more/about'
      preLoaderRoute: typeof MoreAboutRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/clash': {
      id: '/more/clash'
      path: '/clash'
      fullPath: '/more/clash'
      preLoaderRoute: typeof MoreClashRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/explore': {
      id: '/more/explore'
      path: '/explore'
      fullPath: '/more/explore'
      preLoaderRoute: typeof MoreExploreRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/rooms': {
      id: '/more/rooms'
      path: '/rooms'
      fullPath: '/more/rooms'
      preLoaderRoute: typeof MoreRoomsRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/settings': {
      id: '/more/settings'
      path: '/settings'
      fullPath: '/more/settings'
      preLoaderRoute: typeof MoreSettingsRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/share': {
      id: '/more/share'
      path: '/share'
      fullPath: '/more/share'
      preLoaderRoute: typeof MoreShareRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/teachers': {
      id: '/more/teachers'
      path: '/teachers'
      fullPath: '/more/teachers'
      preLoaderRoute: typeof MoreTeachersRouteImport
      parentRoute: typeof MoreRoute
    }
  }
}

interface MoreRouteChildren {
  MoreAboutRoute: typeof MoreAboutRoute
  MoreClashRoute: typeof MoreClashRoute
  MoreExploreRoute: typeof MoreExploreRoute
  MoreRoomsRoute: typeof MoreRoomsRoute
  MoreSettingsRoute: typeof MoreSettingsRoute
  MoreShareRoute: typeof MoreShareRoute
  MoreTeachersRoute: typeof MoreTeachersRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreAboutRoute: MoreAboutRoute,
  MoreClashRoute: MoreClashRoute,
  MoreExploreRoute: MoreExploreRoute,
  MoreRoomsRoute: MoreRoomsRoute,
  MoreSettingsRoute: MoreSettingsRoute,
  MoreShareRoute: MoreShareRoute,
  MoreTeachersRoute: MoreTeachersRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangesRoute: ChangesRoute,
  MoreRoute: MoreRouteWithChildren,
  PrintRoute: PrintRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeekRoute: WeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
